shell = "/usr/bin/zsh"

[window]
  padding = {x = 5, y = 5}
  dynamic_padding = true
  decorations = 'None'
  opacity = 0.80
  blur = true
  startup_mode = 'Maximized'
  option_as_alt = 'OnlyLeft'

[font]
normal = {family = "CodeNewRoman Nerd Font Propo", style = "Regular"}
size= 14
offset = { x = 0, y = 0 }
builtin_box_drawing = false

[colors]
  [colors.primary]
    background = "#1a1b26"
    foreground = "#a9b1d6"

    # Normal colors
  [colors.normal]
    black = "#32344a"
    red = "#f7768e"
    green = "#9ece6a"
    yellow = "#e0af68"
    blue = "#7aa2f7"
    magenta = "#ad8ee6"
    cyan = "#449dab"
    white = "#787c99"

    # Bright colors
  [colors.bright]
    black = "#444b6a"
    red = "#ff7a93"
    green = "#b9f27c"
    yellow = "#ff9e64"
    blue = "#7da6ff"
    magenta = "#bb9af7"
    cyan = "#0db9d7"
    white = "#acb0d0"
 
  [colors.cursor]
    text = "CellBackground"
    cursor = "#d09010"
