import = ["~/.config/alacritty/local.toml"]

# ~/.config/alacritty/local.toml file should contain specific local configuration
# Example:
#
# [window]
#   decorations = "None"
#
# [font]
#   size= 11
#   offset = { x = 0, y = -1 }
#
# [shell]
#   program = "/opt/homebrew/bin/tmux"
#   args = [
#     "new-session",
#     "-A",
#     "-D",
#     "-s",
#     "main",
#   ]

[env]
term = "xterm-256color"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.90
blur = true
decorations = "None"
startup_mode = 'Maximized'
option_as_alt = 'OnlyLeft'

[font]
normal = { family = "CodeNewRoman Nerd Font Propo", style = "Regular" }
builtin_box_drawing = false

# TokyoNight Alacritty Colors (from tokyonight.nvim)
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# [colors.cursor]
#  cursor = '#c0caf5'
#  text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7546e'
green = '#7ece5a'
yellow = '#e3cf48'
blue = '#5a82f7'
magenta = '#bd7af9'
cyan = '#7bfdfd'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#00284f'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[cursor]
style = { shape = "Beam", blinking = "Always" }
thickness = 0.3


[keyboard]
bindings = [
  { key = "C", mods = "Option", action = "WordLeft" },
  { key = "D", mods = "Option", action = "WordRight" },
]
